language: python
python:
  - '3.7'
install:
  - python -V
  - pip install pipenv
  - pipenv install --dev
script:
  - "pipenv run python3 -m pytest services/tests/ --cov=. --cov-report xml:coverage.xml --disable-warnings"
after_success:
  - "pipenv run python-codacy-coverage -r coverage.xml"
