title: The Neon Project Onboarding app

description: |
  Welcome to your new job position at ğŸˆThe Neon ProjectğŸˆ
  --------------------------------------------------------

  We're very happy you wanted to join us, this app will help you with the onboarding
  so you can be coding as soon as possible! ğŸš€
description_apps: First, please check you have all this applications installed, you'll need them soon enough. ğŸ˜
description_services: Please check you have access to all these services
description_footer: Thank you for using our onboarding app ğŸ†

apps:
  fzf: Please check https://github.com/junegunn/fzf#installation for installation
  git: Configure and install git ğŸ“œ on Mac https://www.atlassian.com/git/tutorials/install-git
  code: You can install VS Code ğŸ‘©ğŸ½â€ğŸ’» from https://code.visualstudio.com/, but to use it via command line you also need to install https://code.visualstudio.com/docs/setup/mac#_launching-from-the-command-line
  docker: Install Docker for Mac, you'll need it ğŸ³. https://docs.docker.com/docker-for-mac/
  docker-compose: Install docker-compose to run your docker services all in one https://docs.docker.com/compose/install/

services:
  gmail: Can you access your TNP mail account? https://gmail.com
  abstract: Abstract is Git for designers, so you'll need it to review the wireframes https://www.abstract.com/.
  jira: Here is where we plan, estimate and sprint all the projects https://theneonproject.atlassian.net
  slack: Do you have access to Slack? https://theneonproject.slack.com, you know you can send gifs using `/giphy parrot` command right? ğŸ˜
  github: Here there'll be ğŸ‰ https://github.com/TheNeonProject
  codacy: Our Quality Code service, you need to Signup with your GitHub account, even if you don't use you The Neon Project there https://www.codacy.com/
  factorial: Our HR service, you need to checkin and out here, you can select your holidays and download legal document such as Salary documents https://factorialhr.es/
  heroku: We usually deploy to Heroku, a PaaS, when you need access to the project deployment, we'll give you access accordingly https://dashboard.heroku.com/apps.
  1password: We are concern about security, that' why we use 1Password to store all the passwords and secure notes and related data needed to do our work. https://1password.com/
  zoom: We use Zoom.us to do the dailies and retrospectives
  netelip: (Only if you talk to clients) Voip service in case you need to talk to clients, you can call with this service. https://www.netelip.com/
